#choose base image
FROM node:18-alpine

#set work directory
WORKDIR /app 

#copy package.json to work directory
COPY package.json /app

#install dependencies
RUN npm install

#copy all file to work directory
COPY . . 

#start app
EXPOSE 80

#start app
CMD ["npm","start"]
